version: '3.7'

services:
    php-5.6: &php
        build: docker/php-5.6
        working_dir: /app
        volumes:
            - .:/app
        environment:
            PHP_IDE_CONFIG: serverName=php-cs-fixer
            PHP_CS_FIXER_ALLOW_XDEBUG: 1
        extra_hosts:
            xdebug.remote_host: 172.17.0.1
    php-7.0:
        <<: *php
        build: docker/php-7.0
    php-7.1:
        <<: *php
        build: docker/php-7.1
    php-7.2:
        <<: *php
        build: docker/php-7.2
    php-7.3:
        <<: *php
        build: docker/php-7.3
    php-7.4:
        <<: *php
        build: docker/php-7.4
